### ISSUE TITLE
Server: What's the point of recycling?

### ISSUE THREAD

**Issue by hrefhref** [evadne/gen_magic#15]
While testing `Server.perform` for a long time of continuous calls with random files, memory usage of the apprentice process seems very stable. What is the point of the recycling feature of the server ? libmagic seems certainly safe to use without.

**Comment by evadne** [comment]
I always recycle in order to better cope with unexpected scenarios — if I deploy something I expect it to not require attention for months or years — an explicit recycling mechanism ensures that _if_ there are problems they will be contained. Otherwise all it takes is 1 poison pill and the system goes down. (Obviously, the infrastructure will start the app back up…)
